version: '3.1'

services:
  app:
    image: 'vt-client'
    build: '.'
    ports:
      - 3002:80
    links:
      - server
    depends_on:
      - server

  server:
    image: 'vt-server'
    build: ../vt-server/ # Specify the directory of the Dockerfile
    ports:
      - "3000:3000" # Specify ports for forwarding
    links:
      - database # Link this service to the database service
    volumes:
      - ../vt-server/:/usr/src/server
    depends_on:
      - database

  database:
    image: mongo:latest
