version: '3'

services:
  client:
    build: ./ # Specify the directory of the Dockerfile
    ports:
      - "4200:4200" # Specify ports for forwarding
    links:
      - server
    volumes:
      - .:/usr/src/client
    depends_on:
      - server

  server:
    build: ../vt-server/ # Specify the directory of the Dockerfile
    ports:
      - "3000:3000" # Specify ports for forwarding
    links:
      - database # Link this service to the database service
    volumes:
      - ../vt-server/:/usr/src/server
    depends_on:
      - database

  database:
    image: mongo:latest
